<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Day1" Id="{b71f8504-6820-4310-8889-ac39239075e1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Day1 EXTENDS Common
VAR
	
	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Day1">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>